Fix search/downloads
fallaciousreasoning/CalibreLibgenStore pull request #16
Opened 2023-06-09 18:15 UTC by gstcyr

Still see the odd weird behavior but seems to work well for the most part.

Add more command line tools for testing

2023-06-11 21:25 UTC, fallaciousreasoning commented on libgen_client.py
> +import getopt
Could you move this import into `main` so the plugin still works if `getopt` isn't installed?

2023-06-11 21:26 UTC, fallaciousreasoning commented on libgen_client.py
> +        print(result.title+" by "+result.authors)
Nit: spacing
```suggestion
        print(result.title + " by " + result.authors)
```

2023-06-11 21:27 UTC, fallaciousreasoning commented on libgen_client.py
> +    opts, args = getopt.getopt(argv, "hq:t:a:s:l:f:", ["query=", "title=", "author=", "series=", "language=", "format="])
Personally, I prefer `argparse` for parsing arguments, but this is fine :smile:

2023-06-11 21:28 UTC, fallaciousreasoning commented on libgen_client.py
> +        authors = ' & '.join(filter(None, [
Can this `filter` be removed?

2023-06-11 21:29 UTC, fallaciousreasoning requested changes
Mostly looks pretty good to me, thanks!

2023-06-15 03:32 UTC, gstcyr commented on libgen_client.py
> +        authors = ' & '.join(filter(None, [
I was getting random errors without it

2023-06-15 20:18 UTC, fallaciousreasoning approved these changes
LGTM

2023-06-15 20:18 UTC, merged